- name: Create namespace for arr stack
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: arr-stack
    state: present
  delegate_to: localhost
  become: false

- name: Install Audiobookshelf using local Helm chart
  kubernetes.core.helm:
    name: arr-stack
    chart_ref: "{{ playbook_dir }}/helm_charts/arr_stack"
    release_namespace: media
    create_namespace: false
    values: "{{ arr_stack_values }}"
    state: present
  delegate_to: localhost
  become: false
