apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: {{ .Values.service.webui.port }}
      protocol: TCP
      targetPort: {{ .Values.service.webui.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.webui.nodePort }}
      {{- end }}

    - name: torrent-tcp
      port: {{ .Values.service.torrentTcp.port }}
      protocol: TCP
      targetPort: {{ .Values.service.torrentTcp.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.torrentTcp.nodePort }}
      {{- end }}

    - name: torrent-udp
      port: {{ .Values.service.torrent.port }}
      protocol: UDP
      targetPort: {{ .Values.service.torrent.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.torrent.nodePort }}
      {{- end }}
