- name: Create namespace for Komga
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: komga
    state: present
  delegate_to: localhost
  become: false

- name: Install Komga using local Helm chart
  kubernetes.core.helm:
    name: komga
    chart_ref: "{{ playbook_dir }}/helm_charts/komga"
    release_namespace: media
    create_namespace: false
    values: "{{ komga_values }}"
    state: present
  delegate_to: localhost
  become: false
