- name: Create namespace for Jellyfin
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: media
    state: present
  delegate_to: localhost
  become: false

- name: Install Jellyfin using local Helm chart
  kubernetes.core.helm:
    name: jellyfin
    chart_ref: "{{ playbook_dir }}/helm_charts/jellyfin"
    release_namespace: media
    create_namespace: false
    values: "{{ jellyfin_values }}"
    state: present
  delegate_to: localhost
  become: false
