jellyfin_values:
  service:
    type: NodePort
    port: 8096
    nodePort: 30596

komga_values:
  service:
    type: NodePort
    port: 25600
    nodePort: 3100

audiobookshelf_values:
  service:
    type: NodePort
    port: 80
    nodePort: 3200

nextcloud_values:
  service:
    type: NodePort
    port: 80
    nodePort: 3400

ntfy_values:
  service:
    type: NodePort
    port: 80
    nodePort: 3600

arr_stack_values:
  service:
    type: NodePort
    port: 80
    nodePort: 3600 ####################