jellyfin_values:
  service:
    type: NodePort
    port: 8096
    nodePort: 30596

komga_values:
  service:
    type: NodePort
    port: 25600
    nodePort: 3100

audiobookshelf_values:
  service:
    type: NodePort
    port: 13378
    nodePort: 3200
