- name: Ensure the mount directory exists
  ansible.builtin.file:
    path: "{{ mount_point }}"
    state: directory
    mode: '0777'


- name: Create directory structure
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  loop:
    - "{{ mount_point }}/Media"
    - "{{ mount_point }}/Media/Metadata"
    - "{{ backup_mount_point }}"