- name: Combine primary and backup LVM configs
  set_fact:
    all_lvm_configs: >-
      {{
        [{'volumes': volumes, 'volume_group': volume_group,
          'logical_volumes': logical_volumes, 'mount_point': mount_point}]
        + ([{'volumes': backup_volumes, 'volume_group': backup_volume_group,
             'logical_volumes': backup_logical_volumes, 'mount_point': backup_mount_point}]
           if backup_volumes is defined else [])
      }}

- name: Set up all defined LVMs
  include_tasks: lvm_setup.yaml
  loop: "{{ all_lvm_configs }}"
  loop_control:
    loop_var: lvm_config
