- name: Install nfs-kernel-server package
  become: true
  package:
    name: nfs-kernel-server
    state: present


- name: Ensure NFS exports file contains the correct entry
  lineinfile:
    path: /etc/exports
    line: "{{ mount_point }} *(rw,sync,no_subtree_check,no_root_squash)"
    create: yes
    state: present


- name: Apply the NFS export changes
  command: exportfs -ra


- name: Restart the NFS server service
  systemd:
    name: nfs-kernel-server
    state: restarted


- name: Check the status of the NFS server
  systemd:
    name: nfs-kernel-server
    state: started
    enabled: yes
  register: nfs_status
