- name: Create namespace for NTFY
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: ntfy
    state: present
  delegate_to: localhost
  become: false

- name: Install NTFY using local Helm chart
  kubernetes.core.helm:
    name: ntfy
    chart_ref: "{{ playbook_dir }}/helm_charts/ntfy"
    release_namespace: media
    create_namespace: false
    values: "{{ ntfy_values }}"
    state: present
  delegate_to: localhost
  become: false
