- name: Create namespace for Nextcloud
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: nextcloud
    state: present
  delegate_to: localhost
  become: false

- name: Install Nextcloud using local Helm chart
  kubernetes.core.helm:
    name: nextcloud
    chart_ref: "{{ playbook_dir }}/helm_charts/nextcloud"
    release_namespace: media
    create_namespace: false
    values: "{{ nextcloud_values }}"
    state: present
  delegate_to: localhost
  become: false