#apiVersion: v1
#kind: Service
#metadata:
#  name: bazarr
#spec:
#  selector:
#    app: bazarr
#  ports:
#    - name: http
#      port: {{ .Values.service.port }}
#      targetPort: {{ .Values.service.targetPort }}
#      {{- if .Values.service.nodePort }}
#      nodePort: {{ .Values.service.nodePort }}
#      {{- end }}

apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: bazarr
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
